### PR TITLE
Filter function restored on Bodies and Users

### PR DESCRIPTION
**Pull request by i3anaan**
Making use of Laravel, filters can now be added to any eloquent filter related to bodies and or users.

Example URL:
localhost/api/getUsers?body_name=enschede&name=derk

### CODE REVIEW

**Comment by blacksph3re** [comment]
Can you also do ?anything=derk enschede ? That would be a usecase for the view...

**Comment by i3anaan** [comment]
@blacksph3re Do you mean that you want to search on any field, containing either 'derk' or 'enschede'?

**Comment by i3anaan** [comment]
Currently it really is set up as a filter, meaning this would require every field it searches for to contain the anything argument. Although I do agree this would be really cool to have, I think we can postpone this for a bit later.

**Comment by blacksph3re** [comment]
As your first comment suggests. Do you know those modern "search for anything" inputs? Like what elastic search offeres it is quite handy if you can just enter anything and you don't have to specify a field. Imho that could already make the filtering unnecessary for the first version

**Comment by i3anaan** [comment]
I think I understand what you mean, however, this would require a bit of a different backend approach. Does not mean that these filterings could be really useful in the future (backend and frontend!).

**Comment by blacksph3re** [comment]
Mh, I designed basically all of the search fields to be such fields and sometimes wouldn't even offer the possibility for more detailed filtering but ok, then I would at first shortcut those fields to search the name until we change it to anything

**Comment by i3anaan** [comment]
We should probably look into this:
https://laravel.com/docs/5.4/scout

**Review by blacksph3re — CHANGES_REQUESTED** [review]
You used raw SQL code in quite some places, is that really necessary? That might break DB abstraction...

**Comment by i3anaan** [comment]
I checked and I only found the usage of raw SQL for string management (making things lowercase, concatenating). I can check again if Laravel offers this, otherwise, in my opinion, these are simple enough raw queries that it is acceptable.

**Comment by blacksph3re** [comment]
Okay I also googled it, apparently eloquent doesn't offer any abstraction for this... strange framework

**Review by blacksph3re — APPROVED** [review]

**Pull request merged**
