### PR TITLE
Refactor/api

### PR DESCRIPTION
**Pull request by i3anaan**
First step in standardizing the API. Lots of endpoints have been disabled due to needing a more impactful change in the code, I would rather fix those in upcoming PRs. The ones that are still active and have been tested. All of them have been moved to the new standardized API standards: the URL has been changed and the response format has been changed.

bootstrap/services.php might have to be deleted for ResponseServiceProvider to be seen (bug in Laravel 5.2).

Should merge #12 first

### CODE REVIEW

**Comment by blacksph3re** [comment]
Too much to review, I trust you :D

**Comment by i3anaan** [comment]
Somehow it is not updating the comparison, a lot of these commits are already merged from PR #11 and #12

**Comment by i3anaan** [comment]
You can compare them here:

https://github.com/AEGEE/oms-neo-core/compare/refactor-2...refactor/api?expand=1

**Comment by blacksph3re** [comment]
OK I approve

**Pull request merged**
