### PR TITLE
Refactor/auth

### PR DESCRIPTION
**Pull request by i3anaan**
Utilizes Laravel's Auth facade for authentication.
After login (currently using credentials) an AuthToken is given out same as before, only the initial login is changed to use Laravel's pre-build in functionality.
Overall advantage: Cleaner code through refactoring and utilizing standard framework functionality.

Should merge #16 first

### CODE REVIEW

**Comment by blacksph3re** [comment]
I thought I already commented on that but are you sure the built in auth works with oauth too?

**Comment by blacksph3re** [comment]
Ok more sophisticated: Flaviu told me he actually tried using the built-in auth system but because of our requirements for oauth/office356/google integration he deemed it infeasible. I don't know if he missed up on a feature though and didn't check myself. 

And another point, I think jwts are a good thing to use as they would remove quite some overhead in the microservices for authenticating a user and getting basic user information. For now it's okay to leave it out though but that would have been nice in an auth rewrite.

**Comment by i3anaan** [comment]
Thanks for the comment @blacksph3re !
About the first section, that the build in system was not feasilbe. This is not true, everything we are doing right now we can do as well with the build in auth system, what it mainly adds is some syntactic sugar that gives cleaner code. You can still login any user using Auth::login($user). The benefit of this all is that instead of having to get userData from the Request and seeing then which user is logged in, you can simply call Auth::user(). This combined with some build in checks that are very usefull for credential based login. So to sum up: no functionallity gets lost, cleaner code.

About the JWT, I agree that it is cool, and I also agree this is for a little bit later. However, extending my first part, using Laravel's Auth should not be a limitiation to this.

You can read more of laravel auth here: https://laravel.com/docs/5.2/authentication (note that 5.4 has some file reorganization compared to 5.2)

**Comment by blacksph3re** [comment]
Okay, with that in mind I support this.

**Review by serge1peshcoff — APPROVED** [review]

**Pull request merged**
