### PR TITLE
Added /service/health/ping endpoint

### PR DESCRIPTION
**Pull request by i3anaan**
Actually not 100% sure if this fails before the core is bootstrapped/has db connection.

### CODE REVIEW

**Comment by blacksph3re** [comment]
As this is the sole purpose of that request it would be nice to know that :D maybe you can perform a sample db query and see if that works?

**Comment by i3anaan** [comment]
Okay, it is a little bit more complicating:
I am still not sure if the `service/health/ping` endpoint requires the DB to be running, however I did found out something else:
The DB running does *not* equal the system being boostrapped (which is probably what you want to assertain)
I won't be able to fix this right now, so merge this PR already or wait till I have time :)

**Comment by blacksph3re** [comment]
is this one ready now? Or what was the outcome of the discussion?

**Comment by i3anaan** [comment]
It now does a check whether seeding has completed, although I forgot to include the docker health check, I'd like to add that as well to this.

**Comment by i3anaan** [comment]
Docker health status should be working now, however, I cannot test it currently as I need to rebuild `omscore` and I do not have access to WiFi right now

**Comment by blacksph3re** [comment]
Mh, I am wondering if it's a problem that the healthcheck is on omscore while the api is exposed by omscore-nginx... Docker-swarm would restart that container then, but I don't know if a php app can crash in a way that a restart would solve anything

**Comment by i3anaan** [comment]
That is one of the reasons I implemented a cli check next to the http API.

Although if you want to be fully correct:
omscore is ready when the file system is ready.
Postgres is ready when the dB is ready
Php-fpm is ready when the dB is seeded
Omscore-nginx is ready when it can serve php-fpm

**Comment by blacksph3re** [comment]
No what I meant was that the docker HEALTHCHECK is in omscore, which causes the docker swarm daemon to restart that container. For our system it's perfectly fine like this. I think we will see when we actually  roll it out

**Comment by i3anaan** [comment]
Ah true I guess, will adjust it a bit!

**Comment by i3anaan** [comment]
Ugh:
```
Step 3/11 : HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD php artisan service:health
ERROR: Service 'php-fpm' failed to build: Unknown flag: start-period
```

It works on my machine...

**Pull request merged**
