### PR TITLE
Meta information about permissions

### PR DESCRIPTION
**Pull request by i3anaan**
Ended up rewriting the Response flow, adding a custom Response class, with a semi-hacky implementation. Can probably be improved upon, but will take a lot of time figuring out the Laravel Response class. I'd say leave it like this until it is shown something else is needed.

Improves the permission search phase slightly.

Plays nice with pagination:

```
{
    "success": true,
    "meta": {
        "pagination": {
            "current_page": 1,
            "from": 1,
            "last_page": 1,
            "next_page_url": null,
            "path": "http://localhost/api/users",
            "per_page": 10,
            "prev_page_url": null,
            "to": 6,
            "total": 6
        },
        "permissions": [
            [
                "App\\Models\\User.bodies",
                "App\\Models\\User.pivot"
            ],
            [
                "App\\Models\\User.bodies",
                "App\\Models\\User.pivot"
            ],
            [
                "App\\Models\\User.bodies",
                "App\\Models\\User.pivot",
                "App\\Models\\User.address",
                "App\\Models\\User.circles"
            ],
            [
                "App\\Models\\User.bodies",
                "App\\Models\\User.pivot"
            ],
            [
                "App\\Models\\User.bodies",
                "App\\Models\\User.pivot"
            ],
            [
                "App\\Models\\User.bodies",
                "App\\Models\\User.pivot",
                "App\\Models\\User.address",
                "App\\Models\\User.circles"
            ]
        ]
    },
    "data": [
        {
            "id": 2,
            "address_id": 2,
            "personal_email": "derk.snijders@aegee.org",
            "first_name": "Derk",
            "last_name": "Snijders",
            "date_of_birth": "1993-10-31 00:00:00",
            "gender": "male",
            "phone": null,
            "description": null,
            "remember_token": null,
            "is_superadmin": 1,
            "is_suspended": null,
            "suspended_reason": null,
            "seo_url": "i3anaan",
            "activated_at": "2017-10-08 00:21:36",
            "created_at": "2017-10-08 00:21:36",
            "updated_at": "2017-10-08 00:21:36",
            "internal_email": "derk.snijders@aegee.eu",
            "first_name_simple": "Derk",
            "last_name_simple": "Snijders",
            "bodies": [
                {
                    "id": 2,
                    "type_id": 1,
                    "address_id": 2,
                    "name": "AEGEE-Enschede",
                    "email": "headoffice@aegee.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "ENS",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Enschede",
                    "pivot": {
                        "user_id": 2,
                        "body_id": 2
                    }
                },
                {
                    "id": 4,
                    "type_id": 3,
                    "address_id": 1,
                    "name": "Comité Directeur",
                    "email": "headoffice@aegee.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "DVD",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "Comite Directeur",
                    "pivot": {
                        "user_id": 2,
                        "body_id": 4
                    }
                }
            ]
        },
        {
            "id": 4,
            "address_id": 1,
            "personal_email": "sergey.peshkov@aegee.org",
            "first_name": "Sergey",
            "last_name": "Peshkov",
            "date_of_birth": "1985-04-16 00:00:00",
            "gender": "male",
            "phone": null,
            "description": null,
            "remember_token": null,
            "is_superadmin": 0,
            "is_suspended": null,
            "suspended_reason": null,
            "seo_url": "sergey.peshkov",
            "activated_at": "2017-10-08 00:21:36",
            "created_at": "2017-10-08 00:21:36",
            "updated_at": "2017-10-08 00:21:36",
            "internal_email": null,
            "first_name_simple": "Sergey",
            "last_name_simple": "Peshkov",
            "bodies": [
                {
                    "id": 1,
                    "type_id": 2,
                    "address_id": 1,
                    "name": "AEGEE-Europe",
                    "email": "headoffice@aegee.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "AEU",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Europe",
                    "pivot": {
                        "user_id": 4,
                        "body_id": 1
                    }
                }
            ]
        },
        {
            "id": 5,
            "address_id": 1,
            "personal_email": "fabrizio.bellicano@aegee.org",
            "first_name": "Grace",
            "last_name": "Hopper",
            "date_of_birth": "1985-04-16 00:00:00",
            "gender": "female",
            "phone": null,
            "description": null,
            "remember_token": null,
            "is_superadmin": 0,
            "is_suspended": null,
            "suspended_reason": null,
            "seo_url": "gracehopper",
            "activated_at": "2017-10-08 00:21:36",
            "created_at": "2017-10-08 00:21:36",
            "updated_at": "2017-10-08 00:21:36",
            "internal_email": null,
            "first_name_simple": "Grace",
            "last_name_simple": "Hopper",
            "bodies": [
                {
                    "id": 2,
                    "type_id": 1,
                    "address_id": 2,
                    "name": "AEGEE-Enschede",
                    "email": "headoffice@aegee.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "ENS",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Enschede",
                    "pivot": {
                        "user_id": 5,
                        "body_id": 2
                    }
                },
                {
                    "id": 3,
                    "type_id": 1,
                    "address_id": 3,
                    "name": "AEGEE-Dresden",
                    "email": "info@aegee-dresden.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "DRE",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Dresden",
                    "pivot": {
                        "user_id": 5,
                        "body_id": 3
                    }
                }
            ],
            "address": {
                "id": 1,
                "country_id": 21,
                "street": "Notelaarsstraat 55",
                "zipcode": "1000",
                "city": "Brussels",
                "created_at": "2017-10-08 00:21:36",
                "updated_at": "2017-10-08 00:21:36"
            },
            "circles": []
        },
        {
            "id": 6,
            "address_id": 1,
            "personal_email": "headoffice@aegee.org",
            "first_name": "Big",
            "last_name": "Boobs",
            "date_of_birth": "1998-04-16 00:00:00",
            "gender": "female",
            "phone": null,
            "description": null,
            "remember_token": null,
            "is_superadmin": 0,
            "is_suspended": null,
            "suspended_reason": null,
            "seo_url": "boobies",
            "activated_at": "2017-10-08 00:21:36",
            "created_at": "2017-10-08 00:21:36",
            "updated_at": "2017-10-08 00:21:36",
            "internal_email": null,
            "first_name_simple": "Big",
            "last_name_simple": "Boobs",
            "bodies": [
                {
                    "id": 1,
                    "type_id": 2,
                    "address_id": 1,
                    "name": "AEGEE-Europe",
                    "email": "headoffice@aegee.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "AEU",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Europe",
                    "pivot": {
                        "user_id": 6,
                        "body_id": 1
                    }
                }
            ]
        },
        {
            "id": 1,
            "address_id": 1,
            "personal_email": "admin@aegee.org",
            "first_name": "Super",
            "last_name": "Admin",
            "date_of_birth": "1985-04-16 00:00:00",
            "gender": "other",
            "phone": null,
            "description": null,
            "remember_token": "8HVVHJW8DxYAkXiMZGClVTlOJIeDK1n5QTjJJBRa6Zo4zBzmdGiqMmEHJikW",
            "is_superadmin": 1,
            "is_suspended": null,
            "suspended_reason": null,
            "seo_url": "superadmin",
            "activated_at": "2017-10-08 00:21:36",
            "created_at": "2017-10-08 00:21:36",
            "updated_at": "2017-10-08 00:21:36",
            "internal_email": null,
            "first_name_simple": "Super",
            "last_name_simple": "Admin",
            "bodies": [
                {
                    "id": 1,
                    "type_id": 2,
                    "address_id": 1,
                    "name": "AEGEE-Europe",
                    "email": "headoffice@aegee.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "AEU",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Europe",
                    "pivot": {
                        "user_id": 1,
                        "body_id": 1
                    }
                }
            ]
        },
        {
            "id": 3,
            "address_id": 1,
            "personal_email": "nico.westerbeck@aegee.org",
            "first_name": "Nico",
            "last_name": "Westerbeck",
            "date_of_birth": "1985-04-16 00:00:00",
            "gender": "male",
            "phone": null,
            "description": null,
            "remember_token": "FzyYuM0gj0lssFT3blfx1sSo8b1LqASCI6L5PwLL2Xa3sDJD4viA9rr4O3CG",
            "is_superadmin": 0,
            "is_suspended": null,
            "suspended_reason": null,
            "seo_url": "blacksph3re",
            "activated_at": "2017-10-08 00:21:36",
            "created_at": "2017-10-08 00:21:36",
            "updated_at": "2017-10-08 00:21:36",
            "internal_email": null,
            "first_name_simple": "Nico",
            "last_name_simple": "Westerbeck",
            "address": {
                "id": 1,
                "country_id": 21,
                "street": "Notelaarsstraat 55",
                "zipcode": "1000",
                "city": "Brussels",
                "created_at": "2017-10-08 00:21:36",
                "updated_at": "2017-10-08 00:21:36"
            },
            "bodies": [
                {
                    "id": 3,
                    "type_id": 1,
                    "address_id": 3,
                    "name": "AEGEE-Dresden",
                    "email": "info@aegee-dresden.org",
                    "phone": null,
                    "description": null,
                    "legacy_key": "DRE",
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "AEGEE-Dresden",
                    "pivot": {
                        "user_id": 3,
                        "body_id": 3
                    }
                }
            ],
            "circles": [
                {
                    "id": 5,
                    "body_id": 3,
                    "parent_id": 1,
                    "name": "IT Germany",
                    "description": null,
                    "created_at": "2017-10-08 00:21:36",
                    "updated_at": "2017-10-08 00:21:36",
                    "name_simple": "IT Germany",
                    "pivot": {
                        "user_id": 3,
                        "circle_id": 5
                    }
                }
            ]
        }
    ],
    "message": null
}
```

### CODE REVIEW

**Comment by linuxbandit** [comment]
For this, would it help you to have the graph you asked me (and that I wrote but not scanned and sent yet) ?

**Comment by blacksph3re** [comment]
From a frontend side it would be much more valuable to include POST permissions in this request, as specific editing would mostly happen from the single view and not from the listing. Maybe some less complicated entities such as body types could have it directly in the listing... But still looks nice.

**Comment by i3anaan** [comment]
@linuxbandit Not really, it is hardcoded and demo now anyway, this is more a technological implementation than a real model of AEGEE

@blacksph3re I am not sure if I understand you correctly, when requesting an object (with GET), you already want the permissions you would have for an edit? (POST). I can see that making sense, and might actually be somewhat feasible as it concerns the same context, will look into it.

**Comment by blacksph3re** [comment]
Yeah, when requesting a single one it makes sense from the workflow to have post permissions especially, because the user would not go straight to editing there. Editing would most likely happen with a get of that single resource in between so on the single resource put and delete permissions would be nice to have =)

**Comment by blacksph3re** [comment]
*when requesting a single one => when requesting a listing

**Comment by i3anaan** [comment]
@blacksph3re Ok!, I updated the JIRA issue for it.
https://oms-project.atlassian.net/projects/CORE/issues/CORE-141?filter=allopenissues&orderby=created+DESC%2C+priority+ASC%2C+updated+DESC

**Pull request closed without merging**
