### PR TITLE
Set AuthToken expiration.

### PR DESCRIPTION
**Pull request by i3anaan**
https://oms-project.atlassian.net/projects/CORE/issues/CORE-101?filter=allopenissues

### CODE REVIEW

**Review by linuxbandit — APPROVED** [review]
Ok, can you remind me what's the data structure where the token is saved?

**Comment by i3anaan** [comment]
The AuthToken class, the one that is changed in this PR :P

**Comment by linuxbandit** [comment]
so, sort of "in-memory" ?

**Comment by i3anaan** [comment]
No? This is saved to the database as well, `AuthToken` extends Laravel's `Model` class.
The `save()` call is even in the next line :P

**Comment by linuxbandit** [comment]
Sorry, didn't look the parent :) thanks! It's useful to have it written so I won't finally ask you again lololol

**Pull request merged**
