### PR TITLE
Add Dockerfile, Docker way

### PR DESCRIPTION
**Pull request by linuxbandit**

### CODE REVIEW

**Comment by blacksph3re** [comment]
I am against merging this for reason pointed out in the slack. I find it confusing to have some dockerfiles in their repos and some on oms-docker and prefer having everything in one place. Or otherwise create a repo for every container we have, though that might end up messy as well. At first i think we should stick to having them all in one place, but for automated builds we can rediscuss that later.

**Comment by linuxbandit** [comment]
Ideally we would have every dockerfile in their repo (the *.prod version in your latest PR), which is where oms-docker would take them from, so I don't think there is a confusion. 

In other words, the Dockerfile in every repository will be the main one, then it gets copied (in some automated way, not important now) into oms-docker, where it could (and should) be slightly modified for the *.dev version. In total, just 2 places where the Dockerfiles are, with 2 different types of work

**Comment by blacksph3re** [comment]
As I said I find it confusing to have the .staging and .dev dockerfiles in oms-docker and the .prod ones in their repos. I would put them all into oms-docker as there are some dockerfiles without a repo right now or alternatively create repos for all those Dockerfiles that do not have a repo right now and put all dockerfiles into their repos.

**Comment by serge1peshcoff** [comment]
I agree with Nico that dev's and prod's Dockerfiles should belong in one place, and I like the second approach. I think that Dockerfiles should be in the microservices' repositories.
The point is, we are using not a monolythic approach, but a modular one. I think that the point of microservice architecture is that the modules can be run independently (though there's really not a lot of point in it), and the second approach is better for this.  Otherwise we would have a lot of microservices' repositories which cannot be run by themselves, and an oms-docker repo to run it.
I've also written it at JIRA at the comments, that's how I came to this opinion: https://oms-project.atlassian.net/projects/PROV/issues/PROV-11

**Comment by i3anaan** [comment]
Having played around quite a lot with Docker the past week to get to Laravel 5.4 and to install stuff on Fraktis I think I understand and can comment on this now :)

I believe we should move the Dockerfiles to each repository (if it has one).
I suggest we do not create almost-empty repositories for Dockerfiles that currently do not have a repository yet, and instead leave those in the Docker repository.
Now I am not fully sure I am grasping the benefits of having both staging and production versions (dev I do understand), but putting dev and production into the microservice itself makes sense. Whether to put the staging version in docker I don't really know.


My reasoning:
Same as Sergey says: These microservices should be able to work independently, being dependent on a certain docker repo version kind of ruins this. I encountered a really good example of this myself: I had the need for the php-intl extension, which composer could not install. Having made the code on core and PRing it, I still needed to shoot in a second PR in docker, which kind of shouldn't happen, these should be one (atomic) change. If we had the dev/prod dockerfiles in core this would have been solved.

However, for now, since we seem to have some kind of stability issues in term of branches/directions in oms-docker, let's fix that first.

**Comment by linuxbandit** [comment]
One thing that had me confused btw, isn't staging and dev the same thing? as in, dev is when I develop on my local machine and then I push it to a staging server (I am configuring my EC2 instance for that), but the configuration is the same.

That said, at this point in time it is better to focus on having Dockerfiles in least places possible :D

**Comment by i3anaan** [comment]
The ideas behind this discussion have been implemented by using another branch and are at this point in time merged in develop

**Pull request closed without merging**
